project:
  type: website
  output-dir: docs

website:
  title: "Computational Physics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Getting Started"
        contents:
      - section: "Getting Results"
        contents:
          - tutorials/integration.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



