project:
  type: website
  output-dir: docs

website:
  title: "Computational Physics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - setup.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Getting Started"
        contents:
          - markdown/recap.qmd
          - markdown/quality.qmd
          - markdown/recap_questions.qmd
      - section: "Getting Results"
        contents:
          - section: "Integration"
            contents:
              - href: markdown/integration_introduction.qmd
                text: Introduction
              - notebooks/integration.ipynb
              - notebooks/monte_carlo.ipynb
              - href: markdown/integration_questions.qmd
                text: Questions

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



